### ISSUE TITLE
Proper File Structure 

### ISSUE THREAD

**Issue by rohan-kulkarni-25** [ankitsaxena21/Food-Ordering-App#12]
**Is your feature request related to a problem? Please describe.**
I will like to add a proper file structure so when the project will grow it will be easy to maintain 

**Describe the solution you'd like**
Will like to make 2-3 folder like assets CSS media and script where the particular file can be stored

**Comment by ankitsaxena21** [comment]
Hi @rohan-kulkarni-25 

Sure. You can create PR for it.

Make sure you change all import statements and src links accordingly in the project.

**Comment by rohan-kulkarni-25** [comment]
> 
> 
> Hi @rohan-kulkarni-25
> 
> Sure. You can create a PR for it.
> 
> Make sure you change all import statements and src links accordingly in the project.

I think this will not be required as have changed the html file if there is any update in title with help of javascipt please let me know will check everything once
