### ISSUE TITLE
No Dark mode

### ISSUE THREAD

**Issue by virejdasani** [ankitsaxena21/Food-Ordering-App#19]
The website doesn't have a dark mode. I'd be more than happy to implement it and open a PR. Let me know if that's alright :)

**Comment by ankitsaxena21** [comment]
sure @virejdasani. you can create a PR for it

**Comment by virejdasani** [comment]
@ankitsaxena21, done, https://github.com/ankitsaxena21/Food-Ordering-App/pull/21
