### ISSUE TITLE
Back to top button

### ISSUE THREAD

**Issue by KarishmaVanwari** [ankitsaxena21/Food-Ordering-App#22]
It would be great to add a back to top button on the buttom right corner to enhance user experience.

**Comment by KarishmaVanwari** [comment]
Hey @ankitsaxena21 can I work on this as a part of Hacktoberfest 2021?

**Comment by ankitsaxena21** [comment]
sure @KarishmaVanwari . You can create a PR for it.

**Comment by KarishmaVanwari** [comment]
Could you please add hacktoberfest label and assign me? @ankitsaxena21

**Comment by ankitsaxena21** [comment]
you can create a PR for it. I'll attach the hacktoberfest-accepted label to your PR

**Comment by KarishmaVanwari** [comment]
@ankitsaxena21 Please have a look at #26 
Also, do add hacktoberfest label to my PR if it seems okay.
