### ISSUE TITLE
Bug with Dark Mode

### ISSUE THREAD

**Issue by sagarparmar881** [ankitsaxena21/Food-Ordering-App#23]
Unable to view "Restuarant Name" while on dark mode.

As we do Dark Mode. Font remains in Black color only so it is unable to read, it merges with background.
In short, Issue in dark mode:
Font Color - Black
BG Color - Black

**Comment by tanyasaxena64** [comment]
#25 @ankitsaxena21, I have fixed this issue.

**Comment by ankitsaxena21** [comment]
@sagarparmar881 thank you for reporting this bug.

@tanyasaxena64  thank you for fixing it.
