### ISSUE TITLE
Custom scrollbar

### ISSUE THREAD

**Issue by KarishmaVanwari** [ankitsaxena21/Food-Ordering-App#27]
Adding a custom scrollbar would improve the look of the website.

**Comment by KarishmaVanwari** [comment]
Hey @ankitsaxena21  can I work on this issue as a part of Hacktoberfest 2021, if it's okay with you?
Also, you can let me know your colour preferences, if any.

**Comment by ankitsaxena21** [comment]
Hi @KarishmaVanwari 

Sure. You can create a PR for this.

There's no color preference. But the scroll bar shouldn't look too different from the rest of the site.

**Comment by KarishmaVanwari** [comment]
> Hi @KarishmaVanwari
> 
> Sure. You can create a PR for this.
> 
> There's no color preference. But the scrollbar shouldn't look too different from the rest of the site.

Yeah, the ui of the website will be taken care of.

**Comment by KarishmaVanwari** [comment]
@ankitsaxena21 Have a look at #29 . Also, do add hacktoberfest-accepted label to my PR if it seems okay.
