### ISSUE TITLE
API usage for more and better recommendations

### ISSUE THREAD

**Issue by MilanAgrawal** [ankitsaxena21/Food-Ordering-App#7]
heyy i was thinking if we could use an api of restaurants info and use it in this app

**Comment by ankitsaxena21** [comment]
Hi @MilanAgrawal  ,

Yes, we can use some API for it. But it will require many changes in logic (js part) of the app.

For now I'm just looking for some ui changes in the app.

**Comment by MilanAgrawal** [comment]
ok do you need any help????
I would like to contribute

**Comment by ankitsaxena21** [comment]
It'll be great if you can make some css updates to make the ui look better.
