### ISSUE TITLE
Previous and Next Button margin 

### ISSUE THREAD

**Issue by Subham-dury** [ankitsaxena21/Food-Ordering-App#8]
Sir the next and previous button does not have proper margin around them. 
![Screenshot (445)](https://user-images.githubusercontent.com/65497062/135672719-e55e982f-d182-48fa-b264-ff1278667676.png)

I would like to work on it and fix it. Can you assign me this task?

**Comment by ankitsaxena21** [comment]
Sure @Subham-dury. you can create a PR for it.

**Comment by singlapriyanka315** [comment]
![WhatsApp Image 2021-10-02 at 2 25 48 PM](https://user-images.githubusercontent.com/66158960/135709951-021eba8a-d315-407b-ace5-7a122e966235.jpeg)
opened a pull request
